services:
  neo4j:
    image: neo4j:5.26.0-community
    container_name: snrd-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/import
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USER} -p ${NEO4J_PASSWORD} 'RETURN 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  neo4j_import:
